version: '3'
services:
  web:
    build: .
    ports:
      - '8000:8000'
  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartcity
    ports:
      - '5432:5432'
